# Generated by Django 4.2 on 2023-08-18 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gdscapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teammember',
            name='img',
            field=models.ImageField(upload_to='pics'),
        ),
    ]
