# Generated by Django 4.2 on 2023-08-19 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gdscapp', '0002_alter_teammember_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='teammember',
            name='github',
            field=models.URLField(default='https://github.com'),
        ),
        migrations.AddField(
            model_name='teammember',
            name='linkedin',
            field=models.URLField(default='https://linkedin.com'),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='img',
            field=models.ImageField(default='evergarden.jpeg', upload_to='pics'),
        ),
    ]
