# Generated by Django 4.2 on 2023-08-19 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gdscapp', '0003_teammember_github_teammember_linkedin_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teammember',
            name='img',
            field=models.ImageField(default='https://icons8.com/icon/Hj21JM30swCm/test-account', upload_to='pics'),
        ),
    ]
