# Generated by Django 4.2 on 2023-08-19 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gdscapp', '0004_alter_teammember_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teammember',
            name='img',
            field=models.ImageField(default='pic/evergarden.jpeg', upload_to='pics'),
        ),
    ]
