# Generated by Django 4.2 on 2023-08-19 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gdscapp', '0006_alter_teammember_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teammember',
            name='mobilenumber',
        ),
        migrations.AddField(
            model_name='teammember',
            name='domain',
            field=models.TextField(default='lead', max_length=40),
        ),
        migrations.AddField(
            model_name='teammember',
            name='email',
            field=models.EmailField(default='test@gmail.com', max_length=254),
        ),
        migrations.AddField(
            model_name='teammember',
            name='management',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='teammember',
            name='tech',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='img',
            field=models.ImageField(default='pics/user.png', upload_to='pics'),
        ),
    ]
